name: mindwave_mobile2_example
description: "Demonstrates how to use the mindwave_mobile2 plugin."

publish_to: 'none'

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  mindwave_mobile2:
    path: ../

  cupertino_icons: ^1.0.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_blue_plus:
  fl_chart:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true