name: flutter_mindwave_mobile2
description: "Flutter interface for Neurosky Mindwave Mobile 2 headset."
version: 1.0.0
homepage: https://github.com/PrinceEGY/flutter_mindwave_mobile2

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: org.mindwavemobile2.flutter_mindwave_mobile2
        pluginClass: FlutterMindwaveMobile2Plugin